version: '3'
services:
  api:
    image: nbaghiro/thrive:api_integration
    build: 
      context: ../api
      dockerfile: ./deploy/Dockerfile-integration
  web:
    image: nbaghiro/thrive:web_integration
    build: 
      context: ../web
      dockerfile: ./deploy/Dockerfile-integration
    depends_on:
      - api
  nginx:
    build: ./nginx-integration
    image: nbaghiro/thrive:nginx_integration
    ports:
      - '80:80'
    links:
      - api
      - web
volumes:
  postgres-data: