version: '3'
services:
  api:
    build: 
      context: ../api
      dockerfile: ./deploy/Dockerfile
  web:
    build: 
      context: ../web
      dockerfile: ./deploy/Dockerfile
    depends_on:
      - api
  nginx:
    links:
      - api
      - web
volumes:
  postgres-data: